#!/bin/bash
if [ $# -lt 3 ]
then
    echo "$0 <GWID> <REGION> <TTY> [SAMPLING]"
    exit 1 
fi


GWID=$1
REGION=$2
TTY=$3
SAMPLING=${4:-10}
GWPASS=$(ls_gw_pass $GWID | cut -d " " -f 2 | tail -n1)

cd /home/sgarcia/Programacio/loadsensinggw02/gateway-opkg/production-ls-klkgw/
./setNodeConfig.sh ./fwlib $GWID $GWPASS $REGION $SAMPLING $TTY
cd - &> /dev/null
