#!/usr/bin/python
import serial.tools.list_ports
import os

def find_ttyConnected():
    ttyconnected = {}
    i = 0
    # Search for ttyUSB devices
    list = serial.tools.list_ports.comports()
    for tty in list:
        ttyconnected[str(i)] =  {"dev":  str(tty.device), "type": str(tty).split(" ")[2]}
        i += 1
    print ttyconnected
    return ttyconnected


def is_gw(tty_devices):
    gwtty="disconected"
    for i in sorted(tty_devices.keys()):
        if tty_devices[i]['type'] == 'USB':
            gwtty=i    
    return gwtty

def open_gtkterm():
    print('gtkterm')    


tty_devices = find_ttyConnected()
gw_device = is_gw(tty_devices)
print(gw_device)
os.system("dunstify -a ' GTKTERM: ' -r 5000 -u normal " + str(tty_devices[gw_device]['dev']))

os.system("gtkterm --port " + str(tty_devices[gw_device]['dev']) + " --speed 115200 &")

