# Generated automatically for profile 'home_tri' on 2026-05-19 20:24:01

workspace=1,monitor:desc:AOC 27G2G4 0x00017409,default:true
workspace=2,monitor:desc:AOC 27G2G4 0x00017409
workspace=3,monitor:desc:AOC 27G2G4 0x00017409
workspace=4,monitor:desc:AOC 27G2G4 0x00017409
workspace=5,monitor:desc:AOC 27G2G4 0x00017409
workspace=6,monitor:desc:AOC 27G2G4 0x00017409
workspace=7,monitor:desc:AOC 27G2G4 0x00017409
workspace=8,monitor:desc:AOC 27G2G4 0x00017409
workspace=9,monitor:desc:AOC 27G2G4 0x00017409
workspace=10,monitor:desc:AOC 27G2G4 0x00017409
workspace=11,monitor:desc:Lenovo Group Limited T24i-2L VNA73FRP,default:true
workspace=12,monitor:desc:Lenovo Group Limited T24i-2L VNA73FRP
workspace=13,monitor:desc:Lenovo Group Limited T24i-2L VNA73FRP
workspace=14,monitor:desc:Lenovo Group Limited T24i-2L VNA73FRP
workspace=15,monitor:desc:Lenovo Group Limited T24i-2L VNA73FRP
workspace=16,monitor:desc:Lenovo Group Limited T24i-2L VNA73FRP
workspace=17,monitor:desc:Lenovo Group Limited T24i-2L VNA73FRP
workspace=18,monitor:desc:Lenovo Group Limited T24i-2L VNA73FRP
workspace=19,monitor:desc:Lenovo Group Limited T24i-2L VNA73FRP
workspace=20,monitor:desc:Lenovo Group Limited T24i-2L VNA73FRH
