# Generated automatically for profile 'home' on 2026-04-05 00:22:58

workspace=1,monitor:,default:true
workspace=2,monitor:
workspace=3,monitor:
workspace=4,monitor:
workspace=5,monitor:
workspace=6,monitor:
workspace=7,monitor:
workspace=8,monitor:
workspace=9,monitor:
workspace=10,monitor:
